/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.User;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model.Account;
import javax.swing.JFrame;

/**
 *
 * @author Gekyumeu
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_log_uname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pf_log_pword = new javax.swing.JPasswordField();
        btn_log_login = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant Tagalog");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("RESTAURANT TAGALOG");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, 30, 410, 100);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Don't have an account?");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(60, 450, 150, 20);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 160, 120, 32);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 210, 120, 25);
        jPanel2.add(tf_log_uname);
        tf_log_uname.setBounds(60, 250, 308, 40);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(60, 300, 120, 25);

        pf_log_pword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_log_pwordActionPerformed(evt);
            }
        });
        pf_log_pword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pf_log_pwordKeyPressed(evt);
            }
        });
        jPanel2.add(pf_log_pword);
        pf_log_pword.setBounds(60, 330, 308, 42);

        btn_log_login.setBackground(new java.awt.Color(255, 109, 16));
        btn_log_login.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_log_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_log_login.setText("Login");
        btn_log_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_log_loginActionPerformed(evt);
            }
        });
        jPanel2.add(btn_log_login);
        btn_log_login.setBounds(60, 400, 120, 32);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 51, 255));
        jLabel21.setText("Back to HomePage");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel21);
        jLabel21.setBounds(60, 490, 140, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 51, 255));
        jLabel5.setText("Register here");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);
        jLabel5.setBounds(210, 450, 90, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tomato.png"))); // NOI18N
        jLabel9.setText("jLabel6");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(160, 500, 310, 310);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/grass.png"))); // NOI18N
        jLabel17.setText("jLabel6");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(-20, 520, 320, 300);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/water.png"))); // NOI18N
        jLabel19.setText("jLabel19");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(90, 280, 473, 480);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Untitled design.png"))); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(0, 10, 410, 720);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(490, -20, 410, 730);

        jPanel3.setBackground(new java.awt.Color(255, 109, 16));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Login as Admin");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 660, 490, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/grass.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(270, 400, 320, 300);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/grass.png"))); // NOI18N
        jPanel1.add(jLabel20);
        jLabel20.setBounds(410, 190, 90, 290);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tomato.png"))); // NOI18N
        jLabel15.setText("jLabel15");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(330, 50, 160, 300);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/grass.png"))); // NOI18N
        jPanel1.add(jLabel18);
        jLabel18.setBounds(110, -50, 400, 270);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tomato.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(-110, 470, 290, 290);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/vegg.png"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(60, 410, 360, 340);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/grass.png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(-180, 280, 310, 290);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/grass.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(-140, 40, 400, 290);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/cirle.gif"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(50, 140, 420, 420);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Green Modern Food Recipe Pinterest Pin.png"))); // NOI18N
        jPanel1.add(jLabel22);
        jLabel22.setBounds(-10, -20, 550, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        RegisterChoice regcho = new RegisterChoice();
        regcho.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btn_log_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_log_loginActionPerformed
        // TODO add your handling code here:
        
        User usr = new User();
        
        String username = tf_log_uname.getText().trim();
        String password = new String(pf_log_pword.getPassword());

        int userStatus = usr.RetrieveUserStatus(username, password);

        if(username.equals("") || password.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fields cannot be empty");
        }
        else {
            if (userStatus != -1) {
            JOptionPane.showMessageDialog(null, "Login Successfully");

            if (userStatus == 2) {
                Order ord = new Order();
                ord.setVisible(true);
                dispose();
            } else if (userStatus == 3) {
                StaffDashboard sd = new StaffDashboard();
                sd.setVisible(true);
                dispose();
            }
            } else {
                JOptionPane.showMessageDialog(null, "Wrong Credentials");
            }
        }
    }//GEN-LAST:event_btn_log_loginActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        AdminLogin adlog = new AdminLogin();
        adlog.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void pf_log_pwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pf_log_pwordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            User usr = new User();
        
            String username = tf_log_uname.getText().trim();
            String password = new String(pf_log_pword.getPassword());

            int userStatus = usr.RetrieveUserStatus(username, password);

            if (userStatus != -1) {
                JOptionPane.showMessageDialog(null, "Login Successfully");

                if (userStatus == 2) {
                    Order ord = new Order();
                    ord.setVisible(true);
                    dispose();
                } else if (userStatus == 3) {
                    StaffDashboard sd = new StaffDashboard();
                    sd.setVisible(true);
                    dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Wrong Credentials");
            }
        }
    }//GEN-LAST:event_pf_log_pwordKeyPressed

    private void pf_log_pwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_log_pwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_log_pwordActionPerformed

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        HomePage hp = new HomePage();
        hp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_log_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField pf_log_pword;
    private javax.swing.JTextField tf_log_uname;
    // End of variables declaration//GEN-END:variables
}
