/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
import java.util.Date;
import javax.swing.Timer;
        

/**
 *
 * @author Gekyumeu
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
        setLocationRelativeTo(null);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(180);
        dt(); // daet
        
        times(); // time
        //curDateTime();
    }
    
    
    public void addtable(int id ,String Name, int Qty ,Double Price){

        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();

        DecimalFormat df = new DecimalFormat("00.00") ;       
        double totPrice = Price * Double.valueOf(Qty) ;
       
        String TotalPrice = df.format(totPrice);
        
        for (int row = 0; row < jTable1.getRowCount(); row++) {
            
            if (Name == jTable1.getValueAt(row, 1)) {
                
                dt.removeRow(jTable1.convertRowIndexToModel(row));
                
            } 
        }
        
        Vector v = new Vector();

        v.add(id);
        v.add(Name);
        v.add(Qty);
        v.add(TotalPrice);

        dt.addRow(v);
    }
    
    public void cal(){
    //cal total table values
   
    int numOfRow = jTable1.getRowCount() ;
    double tot = 0.0 ;
   
       for (int i = 0; i < numOfRow; i++) {
           
           double value = Double.valueOf(jTable1.getValueAt(i, 3).toString());
          
           tot += value ;
           
        }
        
        DecimalFormat df = new DecimalFormat("00.00") ;
        total.setText(df.format(tot));
   }

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new button.MyButton();
        jButton2 = new button.MyButton();
        jButton3 = new button.MyButton();
        jLabel11 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        q1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        q2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        q3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        q4 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        q5 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        q6 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        q7 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        q8 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        q9 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        q10 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        q11 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        q12 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        q13 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        q14 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        q15 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        q16 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        q17 = new javax.swing.JLabel();
        jButton23 = new javax.swing.JButton();
        q18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton24 = new javax.swing.JButton();
        q19 = new javax.swing.JLabel();
        jButton25 = new javax.swing.JButton();
        q20 = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();
        q21 = new javax.swing.JLabel();
        jButton27 = new javax.swing.JButton();
        q22 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        q23 = new javax.swing.JLabel();
        jButton29 = new javax.swing.JButton();
        q24 = new javax.swing.JLabel();
        jButton30 = new javax.swing.JButton();
        q25 = new javax.swing.JLabel();
        jButton31 = new javax.swing.JButton();
        q26 = new javax.swing.JLabel();
        jButton32 = new javax.swing.JButton();
        q27 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        l_date = new javax.swing.JTextField();
        l_time = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        pay = new javax.swing.JTextField();
        total = new javax.swing.JLabel();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        b = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bal1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel8.setBackground(new java.awt.Color(255, 51, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/background_ordering.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 860, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 860, 110));

        jPanel6.setBackground(new java.awt.Color(255, 102, 0));
        jPanel6.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/main.meal.trans.png"))); // NOI18N
        jButton1.setText("                                         sdsdsdsds  ");
        jButton1.setBorderColor(new java.awt.Color(51, 51, 51));
        jButton1.setColor(new java.awt.Color(255, 102, 0));
        jButton1.setColorClick(new java.awt.Color(255, 255, 255));
        jButton1.setColorOver(new java.awt.Color(204, 204, 204));
        jButton1.setPreferredSize(new java.awt.Dimension(283, 162));
        jButton1.setRadius(100);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);
        jButton1.setBounds(10, 190, 290, 100);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/drinks.trans.png"))); // NOI18N
        jButton2.setText("                  ");
        jButton2.setBorderColor(new java.awt.Color(51, 51, 51));
        jButton2.setColor(new java.awt.Color(255, 102, 0));
        jButton2.setColorClick(new java.awt.Color(255, 255, 255));
        jButton2.setColorOver(new java.awt.Color(204, 204, 204));
        jButton2.setRadius(100);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);
        jButton2.setBounds(10, 300, 283, 90);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dessert.trans (1).png"))); // NOI18N
        jButton3.setText("                  ");
        jButton3.setBorderColor(new java.awt.Color(51, 51, 51));
        jButton3.setColor(new java.awt.Color(255, 102, 0));
        jButton3.setColorClick(new java.awt.Color(255, 255, 255));
        jButton3.setColorOver(new java.awt.Color(204, 204, 204));
        jButton3.setRadius(100);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);
        jButton3.setBounds(0, 400, 250, 100);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/Please.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(20, 0, 200, 180);

        jPanel8.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 100, 230, 510));

        jTabbedPane2.setBackground(new java.awt.Color(153, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 102, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        q1.setBackground(new java.awt.Color(255, 255, 255));
        q1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q1.setForeground(new java.awt.Color(255, 255, 255));
        q1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q1.setText("0");
        jPanel5.add(q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 60, 40));

        jButton6.setBackground(new java.awt.Color(255, 204, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOOD MENU/ADOBONG BABOY.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 180));

        q2.setBackground(new java.awt.Color(255, 255, 255));
        q2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q2.setForeground(new java.awt.Color(255, 255, 255));
        q2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q2.setText("0");
        jPanel5.add(q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 50, 40));

        jButton7.setBackground(new java.awt.Color(255, 204, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOOD MENU/TOGUE DE PANSIT.png"))); // NOI18N
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 200, 180));

        q3.setBackground(new java.awt.Color(255, 255, 255));
        q3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q3.setForeground(new java.awt.Color(255, 255, 255));
        q3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q3.setText("0");
        jPanel5.add(q3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 50, 40));

        jButton8.setBackground(new java.awt.Color(255, 204, 0));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOOD MENU/ALPHA DE PAPA.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 200, 180));

        q4.setBackground(new java.awt.Color(255, 255, 255));
        q4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q4.setForeground(new java.awt.Color(255, 255, 255));
        q4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q4.setText("0");
        jPanel5.add(q4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 60, 40));

        jButton9.setBackground(new java.awt.Color(255, 204, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOOD MENU/GULAY DE LAMAN.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 200, 180));

        q5.setBackground(new java.awt.Color(255, 255, 255));
        q5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q5.setForeground(new java.awt.Color(255, 255, 255));
        q5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q5.setText("0");
        jPanel5.add(q5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 50, 40));

        jButton10.setBackground(new java.awt.Color(255, 204, 0));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOOD MENU/CHICKEN DE BIRYANI.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 200, 180));

        q6.setBackground(new java.awt.Color(255, 255, 255));
        q6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q6.setForeground(new java.awt.Color(255, 255, 255));
        q6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q6.setText("0");
        jPanel5.add(q6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 50, 40));

        jButton11.setBackground(new java.awt.Color(255, 204, 0));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOOD MENU/MANOK DE SINIGANG.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 200, 180));

        q7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q7.setForeground(new java.awt.Color(255, 255, 255));
        q7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q7.setText("0");
        jPanel5.add(q7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 70, 40));

        jButton12.setBackground(new java.awt.Color(255, 204, 0));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOOD MENU/LOMI DE MAMA.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 200, 180));

        q8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q8.setForeground(new java.awt.Color(255, 255, 255));
        q8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q8.setText("0");
        jPanel5.add(q8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 60, 40));

        jButton13.setBackground(new java.awt.Color(255, 204, 0));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOOD MENU/DE PANSIT BIHON.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 200, 180));

        q9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q9.setForeground(new java.awt.Color(255, 255, 255));
        q9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q9.setText("0");
        jPanel5.add(q9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 60, 40));

        jButton14.setBackground(new java.awt.Color(255, 204, 0));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOOD MENU/TAPA DE ASUKAL.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 200, 180));

        jLabel8.setBackground(new java.awt.Color(229, 122, 31));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOOD MENU/bc.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 130, 690, 580));

        jTabbedPane2.addTab("tab2", jPanel5);

        jPanel3.setBackground(new java.awt.Color(255, 109, 16));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        q10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q10.setForeground(new java.awt.Color(255, 255, 255));
        q10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q10.setText("0");
        jPanel3.add(q10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 200, 40));

        jButton15.setBackground(new java.awt.Color(255, 204, 0));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOOD MENU/RICE.png"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 200, 180));

        jButton16.setBackground(new java.awt.Color(255, 204, 0));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOOD MENU/WATER.png"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 200, 180));

        q11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q11.setForeground(new java.awt.Color(255, 255, 255));
        q11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q11.setText("0");
        jPanel3.add(q11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 200, 40));

        jButton17.setBackground(new java.awt.Color(255, 204, 0));
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOOD MENU/ROYAL SOFTDRINKS.png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 200, 180));

        q12.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q12.setForeground(new java.awt.Color(255, 255, 255));
        q12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q12.setText("0");
        jPanel3.add(q12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 200, 40));

        jButton18.setBackground(new java.awt.Color(255, 204, 0));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOOD MENU/COKE CAN.png"))); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 200, 180));

        q13.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q13.setForeground(new java.awt.Color(255, 255, 255));
        q13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q13.setText("0");
        jPanel3.add(q13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, 200, 40));

        jButton19.setBackground(new java.awt.Color(255, 204, 0));
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOOD MENU/COKE LARGE.png"))); // NOI18N
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 200, 180));

        q14.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q14.setForeground(new java.awt.Color(255, 255, 255));
        q14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q14.setText("0");
        jPanel3.add(q14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 700, 200, 40));

        jButton20.setBackground(new java.awt.Color(255, 204, 0));
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOOD MENU/MOUNTAIN DEW.png"))); // NOI18N
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 200, 180));

        q15.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q15.setForeground(new java.awt.Color(255, 255, 255));
        q15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q15.setText("0");
        jPanel3.add(q15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 700, 200, 40));

        jButton21.setBackground(new java.awt.Color(255, 204, 0));
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOOD MENU/VINEGAR SAUCE.png"))); // NOI18N
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 760, 200, 180));

        q16.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q16.setForeground(new java.awt.Color(255, 255, 255));
        q16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q16.setText("0");
        jPanel3.add(q16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 940, 200, 40));

        jButton22.setBackground(new java.awt.Color(255, 204, 0));
        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOOD MENU/SOY SAUCE.png"))); // NOI18N
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 760, 200, 180));

        q17.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q17.setForeground(new java.awt.Color(255, 255, 255));
        q17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q17.setText("0");
        jPanel3.add(q17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 940, 200, 40));

        jButton23.setBackground(new java.awt.Color(255, 204, 0));
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOOD MENU/PINEAPPLE JUICE.png"))); // NOI18N
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 760, 200, 180));

        q18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOOD MENU/bc.png"))); // NOI18N
        q18.setText("jLabel8");
        jPanel3.add(q18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 670, 720));

        jTabbedPane2.addTab("tab3", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 102, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/1.jpg"))); // NOI18N
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 326, 192, 155));

        q19.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q19.setText("0");
        jPanel4.add(q19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 487, 192, 40));

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/1.jpg"))); // NOI18N
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 326, 192, 155));

        q20.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q20.setText("0");
        jPanel4.add(q20, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 487, 192, 40));

        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/1.jpg"))); // NOI18N
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 326, 192, 155));

        q21.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q21.setText("0");
        jPanel4.add(q21, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 487, 192, 40));

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/1.jpg"))); // NOI18N
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 545, 192, 155));

        q22.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q22.setText("0");
        jPanel4.add(q22, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 706, 192, 40));

        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/1.jpg"))); // NOI18N
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 545, 192, 155));

        q23.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q23.setText("0");
        jPanel4.add(q23, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 706, 192, 40));

        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/1.jpg"))); // NOI18N
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 545, 192, 155));

        q24.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q24.setText("0");
        jPanel4.add(q24, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 706, 192, 40));

        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/1.jpg"))); // NOI18N
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 764, 192, 155));

        q25.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q25.setText("0");
        jPanel4.add(q25, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 925, 192, 40));

        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/1.jpg"))); // NOI18N
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 764, 192, 155));

        q26.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q26.setText("0");
        jPanel4.add(q26, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 925, 192, 40));

        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/1.jpg"))); // NOI18N
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 764, 192, 155));

        q27.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        q27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q27.setText("0");
        jPanel4.add(q27, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 925, 192, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOOD MENU/bc.png"))); // NOI18N
        jLabel10.setText("jLabel8");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 670, 810));

        jTabbedPane2.addTab("tab1", jPanel4);

        jPanel8.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, -66, 670, 770));

        jPanel7.setBackground(new java.awt.Color(255, 102, 0));
        jPanel7.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("UserName");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel12);
        jLabel12.setBounds(80, 0, 70, 20);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("/ ID");
        jPanel7.add(jLabel13);
        jLabel13.setBounds(150, 20, 24, 20);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ADDRESS");
        jPanel7.add(jLabel14);
        jLabel14.setBounds(80, 20, 62, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/profile picture.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel7.add(jLabel7);
        jLabel7.setBounds(0, 0, 75, 76);

        l_date.setEditable(false);
        l_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_dateActionPerformed(evt);
            }
        });
        jPanel7.add(l_date);
        l_date.setBounds(110, 40, 110, 30);

        l_time.setEditable(false);
        jPanel7.add(l_time);
        l_time.setBounds(110, 70, 110, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Date");
        jPanel7.add(jLabel4);
        jLabel4.setBounds(80, 50, 29, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Time");
        jPanel7.add(jLabel6);
        jLabel6.setBounds(80, 80, 29, 20);

        jButton4.setText("Logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4);
        jButton4.setBounds(170, 0, 72, 23);

        jPanel8.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 240, 100));

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Item", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTable1MouseDragged(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 100, 240, 210));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Total:");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 550, -1, 20));

        pay.setBackground(new java.awt.Color(255, 255, 255));
        pay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel8.add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 570, 180, 23));

        total.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        total.setForeground(new java.awt.Color(0, 0, 0));
        total.setText("00");
        jPanel8.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 550, -1, -1));

        jButton35.setBackground(new java.awt.Color(255, 204, 0));
        jButton35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton35.setForeground(new java.awt.Color(0, 0, 0));
        jButton35.setText("PAY");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 612, 70, 60));

        jButton36.setBackground(new java.awt.Color(255, 204, 0));
        jButton36.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton36.setForeground(new java.awt.Color(0, 0, 0));
        jButton36.setText("PRINT");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 640, -1, 30));

        jButton5.setBackground(new java.awt.Color(255, 204, 0));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("DELETE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 540, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        b.setEditable(false);
        b.setBackground(new java.awt.Color(255, 255, 255));
        b.setColumns(20);
        b.setRows(5);
        jScrollPane2.setViewportView(b);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 310, 240, 230));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Balance:");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 590, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Cash:");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 570, -1, 20));

        bal1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bal1.setForeground(new java.awt.Color(0, 0, 0));
        bal1.setText("00");
        jPanel8.add(bal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 590, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        
        jTabbedPane2.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTabbedPane2.setSelectedIndex(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q1.getText());
        ++i;
        q1.setText(String.valueOf(i));
        
        addtable(1, "Adobo  ", i, 60.00);
        
        cal();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q2.getText());
        ++i;
        q2.setText(String.valueOf(i));
        
        addtable(2, "Togue De Pansit  ", i, 60.00);
        
        cal();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q3.getText());
        ++i;
        q3.setText(String.valueOf(i));
        
        addtable(3, "Alpha de Papa ", i, 150.00);
        
        cal();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q4.getText());
        ++i;
        q4.setText(String.valueOf(i));
        
        addtable(4, "Gulay de Laman  ", i, 1000.00);
        
        cal();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q5.getText());
        ++i;
        q5.setText(String.valueOf(i));
        
        addtable(5, "Chicken De Biryani", i, 600.00);
        
        cal();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q6.getText());
        ++i;
        q6.setText(String.valueOf(i));
        
        addtable(6, "Manok de Sinigang ", i, 100.00);
        
        cal();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q7.getText());
        ++i;
        q7.setText(String.valueOf(i));
        
        addtable(7, "Lomi de Mama", i, 100.00);
        
        cal();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q8.getText());
        ++i;
        q8.setText(String.valueOf(i));
        
        addtable(8, "De Pancit Bihon", i, 450.00);
        
        cal();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q9.getText());
        ++i;
        q9.setText(String.valueOf(i));
        
        addtable(9, "Tapa de Asukal", i, 250.00);
        
        cal();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
        // pat btn
        
        double tot = Double.valueOf(total.getText());
        double paid = Double.valueOf(pay.getText());
        double balance = paid - tot ;
                
        DecimalFormat df = new DecimalFormat("00.00") ;   
       
       
        total.setText(String.valueOf(df.format(balance)));
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        String r = dt.getValueAt(jTable1.getSelectedRow(), 0).toString();

        //remove product
        int rw = jTable1.getSelectedRow();
        dt.removeRow(rw);

        //remove Qty Lable
        System.out.println(r);
        switch (r) {

            case "1":
            q1.setText("0");
            break;

            case "2":
            q2.setText("0");
            break;

            case "3":
            q3.setText("0");
            break;

            case "4":
            q4.setText("0");
            break;

            case "5":
            q5.setText("0");
            break;

            case "6":
            q6.setText("0");

            case "7":
            q7.setText("0");
            break;

            case "8":
            q8.setText("0");
            break;

            case "9":
            q9.setText("0");
            break;

            default:
            System.out.println("over");
        }

        cal();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:
        try {
            
           b.setText("                         RESTAURANT TAGALOG \n");
            b.setText(b.getText() + "                         589/ NCST OOP PROJECT, \n");
            b.setText(b.getText() + "                         DASMARIÑAS CAVITE, PHILIPPINES, \n");
            b.setText(b.getText() + "                         +09123456789, \n");
            b.setText(b.getText() + "---------------------------------------------------------------------\n");
            b.setText(b.getText() + "  Item \t\tQty \tPrice" +"\n");
            b.setText(b.getText() + "---------------------------------------------------------------------\n");
            
            DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
            
            // get table Product details
            
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                
                String Name = df.getValueAt(i, 1).toString();
                String Qty = df.getValueAt(i, 2).toString();
                String Price = df.getValueAt(i, 3).toString();
                
                b.setText(b.getText() +"  "+ Name+"\t\t"+Qty +"\t"+Price + "\n");
            }
            
            b.setText(b.getText() + "---------------------------------------------------------------------\n");
            b.setText(b.getText() + "Sub Total : " + total.getText() +"\n");
            b.setText(b.getText() + "Cash      : " + pay.getText() +"\n");
            b.setText(b.getText() + "Balance   : " + total.getText() +"\n");
            b.setText(b.getText() + "---------------------------------------------------------------------\n");
            b.setText(b.getText() + "                     Thanks For Your Business...!"+"\n");
            b.setText(b.getText() + "---------------------------------------------------------------------\n");
            b.setText(b.getText() + "                     Brought to you by Nestler and JM"+"\n");
            
           
        b.print(); //print
            
            
        } catch (Exception e) {
            
            System.out.println(e);
            
            
        }
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q10.getText());
        ++i;
        q10.setText(String.valueOf(i));
        
        addtable(10, "Plain Rice", i, 30.00);
        
        cal();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void l_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_dateActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        CustomerDashboard cusdash = new CustomerDashboard();
        cusdash.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q11.getText());
        ++i;
        q11.setText(String.valueOf(i));
        
        addtable(11, "Bottled Water", i, 25.00);
        
        cal();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q12.getText());
        ++i;
        q12.setText(String.valueOf(i));
        
        addtable(12, "Royal Softdrinks", i, 40.00);
        
        cal();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q13.getText());
        ++i;
        q13.setText(String.valueOf(i));
        
        addtable(13, "Coke Can", i, 45.00);
        
        cal();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jTable1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseDragged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q14.getText());
        ++i;
        q14.setText(String.valueOf(i));
        
        addtable(14, "Coke Large", i, 120.00);
        
        cal();
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q15.getText());
        ++i;
        q15.setText(String.valueOf(i));
        
        addtable(15, "Mountain Dew", i, 70.00);
        
        cal();
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q16.getText());
        ++i;
        q16.setText(String.valueOf(i));
        
        addtable(16, "16th beverage", i, 120.00);
        
        cal();
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q17.getText());
        ++i;
        q17.setText(String.valueOf(i));
        
        addtable(17, "17th beverage", i, 120.00);
        
        cal();
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q18.getText());
        ++i;
        q18.setText(String.valueOf(i));
        
        addtable(18, "18th beverage", i, 120.00);
        
        cal();
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q19.getText());
        ++i;
        q19.setText(String.valueOf(i));
        
        addtable(19, "19th dessert", i, 120.00);
        
        cal();
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q20.getText());
        ++i;
        q20.setText(String.valueOf(i));
        
        addtable(20, "20th dessert", i, 120.00);
        
        cal();
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q21.getText());
        ++i;
        q21.setText(String.valueOf(i));
        
        addtable(21, "21st dessert", i, 120.00);
        
        cal();
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q22.getText());
        ++i;
        q22.setText(String.valueOf(i));
        
        addtable(22, "22st dessert", i, 120.00);
        
        cal();
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q23.getText());
        ++i;
        q23.setText(String.valueOf(i));
        
        addtable(23, "23rd dessert", i, 120.00);
        
        cal();
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q24.getText());
        ++i;
        q24.setText(String.valueOf(i));
        
        addtable(24, "24th dessert", i, 120.00);
        
        cal();
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q25.getText());
        ++i;
        q25.setText(String.valueOf(i));
        
        addtable(25, "25th dessert", i, 120.00);
        
        cal();
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q26.getText());
        ++i;
        q26.setText(String.valueOf(i));
        
        addtable(26, "26th dessert", i, 120.00);
        
        cal();
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q27.getText());
        ++i;
        q27.setText(String.valueOf(i));
        
        addtable(27, "27th dessert", i, 120.00);
        
        cal();
    }//GEN-LAST:event_jButton32ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    /*
    public void curDateTime() {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        dateTime.setText(dtf.format(now));
    }
    */
    
    public void dt(){

    Date d  =new Date();
    
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MMM-dd");
    
    String dd = sdf.format(d);
    l_date.setText(dd);


}
   
// time
 Timer t ;
 SimpleDateFormat st ;
    
public void times(){

   
    
  t = new Timer(0, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        
        Date dt  =new Date();
        st = new SimpleDateFormat("hh:mm:ss");
        
        String tt = st.format(dt);
        l_time.setText(tt);  
        
        }
    });
  
    t.start();
    
    

}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
              
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea b;
    private javax.swing.JLabel bal1;
    private button.MyButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private button.MyButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private button.MyButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField l_date;
    private javax.swing.JTextField l_time;
    private javax.swing.JTextField pay;
    private javax.swing.JLabel q1;
    private javax.swing.JLabel q10;
    private javax.swing.JLabel q11;
    private javax.swing.JLabel q12;
    private javax.swing.JLabel q13;
    private javax.swing.JLabel q14;
    private javax.swing.JLabel q15;
    private javax.swing.JLabel q16;
    private javax.swing.JLabel q17;
    private javax.swing.JLabel q18;
    private javax.swing.JLabel q19;
    private javax.swing.JLabel q2;
    private javax.swing.JLabel q20;
    private javax.swing.JLabel q21;
    private javax.swing.JLabel q22;
    private javax.swing.JLabel q23;
    private javax.swing.JLabel q24;
    private javax.swing.JLabel q25;
    private javax.swing.JLabel q26;
    private javax.swing.JLabel q27;
    private javax.swing.JLabel q3;
    private javax.swing.JLabel q4;
    private javax.swing.JLabel q5;
    private javax.swing.JLabel q6;
    private javax.swing.JLabel q7;
    private javax.swing.JLabel q8;
    private javax.swing.JLabel q9;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
